In [131]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as py

In [132]:
df = pd.read_csv('listings.csv', low_memory=False)

In [133]:
print(df)

            id                            listing_url       scrape_id  \
0          958       https://www.airbnb.com/rooms/958  20191204162709
1         3850      https://www.airbnb.com/rooms/3850  20191204162709
2         5858      https://www.airbnb.com/rooms/5858  20191204162709
3         7918      https://www.airbnb.com/rooms/7918  20191204162709
4         8142      https://www.airbnb.com/rooms/8142  20191204162709
...        ...                                    ...             ...
8528  40544136  https://www.airbnb.com/rooms/40544136  20191204162709
8529  40546145  https://www.airbnb.com/rooms/40546145  20191204162709
8530  40547706  https://www.airbnb.com/rooms/40547706  20191204162709
8531  40560328  https://www.airbnb.com/rooms/40560328  20191204162709
8532  40569280  https://www.airbnb.com/rooms/40569280  20191204162709

     last_scraped                                               name  \
0      2019-12-04                Bright, Modern Garden Unit - 1BR/1B
1      2019-12-04                              Charming room for two
2      2019-12-05                                 Creative Sanctuary
3      2019-12-04         A Friendly Room - UCSF/USF - San Francisco
4      2019-12-04  Friendly Room Apt. Style -UCSF/USF - San Franc...
...           ...                                                ...
8528   2019-12-04  Entire apartment in Pacific Heights/beautiful ...
8529   2019-12-04        Huge Private Room; 8 min to Dwntwn SF & SFO
8530   2019-12-04              Welcome onboard a beautiful Sailboat!
8531   2019-12-04  Lg 1 Bed/1 Bath w/ Living & Dining Rm in Top Area
8532   2019-12-04  Clean Spacious Room in Central SF Flat - 30 Da...

                                                summary  \
0     New update: the house next door is under const...
1     Your own private room plus access to a shared ...
2                                                   NaN
3     Nice and good public transportation.  7 minute...
4     Nice and good public transportation.  7 minute...
...                                                 ...
8528  A place for zen with a beautiful patio and bac...
8529  We are kind and friendly people looking for wo...
8530  Experience a beautiful and cozy, spacious and ...
8531  (This same unit, listed as a 2 bedroom has 5 o...
8532  Located in the heart of the Mission District, ...

                                                  space  \
0     Newly remodeled, modern, and bright garden uni...
1     This room can fit two people. Nobody else will...
2     We live in a large Victorian house on a quiet ...
3     Settle down, S.F. resident, student, hospital,...
4     Settle down, S.F. resident, student, hospital,...
...                                                 ...
8528                                                NaN
8529                                                NaN
8530  The boat comes furnished with blankets, small ...
8531  This very large 1 bedroom/1 bathroom/living ro...
8532  I have custom designed this home for our famil...

                                            description experiences_offered  \
0     New update: the house next door is under const...                none
1     Your own private room plus access to a shared ...                none
2     We live in a large Victorian house on a quiet ...                none
3     Nice and good public transportation.  7 minute...                none
4     Nice and good public transportation.  7 minute...                none
...                                                 ...                 ...
8528  A place for zen with a beautiful patio and bac...                none
8529  We are kind and friendly people looking for wo...                none
8530  Experience a beautiful and cozy, spacious and ...                none
8531  (This same unit, listed as a 2 bedroom has 5 o...                none
8532  Located in the heart of the Mission District, ...                none

                                  neighborhood_overview  ... instant_bookable  \
0     *Quiet cul de sac in friendly neighborhood *St...  ...                f
1     This is a quiet, safe neighborhood on a substa...  ...                f
2     I love how our neighborhood feels quiet but is...  ...                f
3     Shopping old town, restaurants, McDonald, Whol...  ...                f
4                                                   NaN  ...                f
...                                                 ...  ...              ...
8528                                                NaN  ...                t
8529                                                NaN  ...                t
8530  The Location : Treasure Island Marina  offers ...  ...                t
8531  There are 2 parks in the neighborhood. There i...  ...                f
8532  In my totally biased opinion: the Mission dist...  ...                t

     is_business_travel_ready          cancellation_policy  \
0                           f                     moderate
1                           f  strict_14_with_grace_period
2                           f  strict_14_with_grace_period
3                           f  strict_14_with_grace_period
4                           f  strict_14_with_grace_period
...                       ...                          ...
8528                        f                     flexible
8529                        f                     flexible
8530                        f                     moderate
8531                        f                     moderate
8532                        f  strict_14_with_grace_period

     require_guest_profile_picture require_guest_phone_verification  \
0                                f                                f
1                                f                                f
2                                f                                f
3                                f                                f
4                                f                                f
...                            ...                              ...
8528                             f                                f
8529                             f                                f
8530                             f                                f
8531                             f                                f
8532                             f                                f

      calculated_host_listings_count  \
0                                  1
1                                  3
2                                  1
3                                  9
4                                  9
...                              ...
8528                               2
8529                               2
8530                               1
8531                               2
8532                               8

      calculated_host_listings_count_entire_homes  \
0                                               1
1                                               0
2                                               1
3                                               0
4                                               0
...                                           ...
8528                                            1
8529                                            0
8530                                            1
8531                                            2
8532                                            1

     calculated_host_listings_count_private_rooms  \
0                                               0
1                                               3
2                                               0
3                                               9
4                                               9
...                                           ...
8528                                            1
8529                                            2
8530                                            0
8531                                            0
8532                                            7

      calculated_host_listings_count_shared_rooms  reviews_per_month
0                                               0               1.79
1                                               0               1.38
2                                               0               0.86
3                                               0               0.14
4                                               0               0.13
...                                           ...                ...
8528                                            0                NaN
8529                                            0                NaN
8530                                            0                NaN
8531                                            0                NaN
8532                                            0                NaN

[8533 rows x 106 columns]

In [134]:
df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,958,https://www.airbnb.com/rooms/958,20191204162709,2019-12-04,"Bright, Modern Garden Unit - 1BR/1B",New update: the house next door is under const...,"Newly remodeled, modern, and bright garden uni...",New update: the house next door is under const...,none,*Quiet cul de sac in friendly neighborhood *St...,...,f,f,moderate,f,f,1,1,0,0,1.79
1,3850,https://www.airbnb.com/rooms/3850,20191204162709,2019-12-04,Charming room for two,Your own private room plus access to a shared ...,This room can fit two people. Nobody else will...,Your own private room plus access to a shared ...,none,"This is a quiet, safe neighborhood on a substa...",...,f,f,strict_14_with_grace_period,f,f,3,0,3,0,1.38
2,5858,https://www.airbnb.com/rooms/5858,20191204162709,2019-12-05,Creative Sanctuary,NaN,We live in a large Victorian house on a quiet ...,We live in a large Victorian house on a quiet ...,none,I love how our neighborhood feels quiet but is...,...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,0.86
3,7918,https://www.airbnb.com/rooms/7918,20191204162709,2019-12-04,A Friendly Room - UCSF/USF - San Francisco,Nice and good public transportation. 7 minute...,"Settle down, S.F. resident, student, hospital,...",Nice and good public transportation. 7 minute...,none,"Shopping old town, restaurants, McDonald, Whol...",...,f,f,strict_14_with_grace_period,f,f,9,0,9,0,0.14
4,8142,https://www.airbnb.com/rooms/8142,20191204162709,2019-12-04,Friendly Room Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,"Settle down, S.F. resident, student, hospital,...",Nice and good public transportation. 7 minute...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,9,0,9,0,0.13

In [135]:
df.shape

(8533, 106)

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8533 entries, 0 to 8532
Columns: 106 entries, id to reviews_per_month
dtypes: float64(23), int64(21), object(62)
memory usage: 6.9+ MB

In [137]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8533 entries, 0 to 8532
Data columns (total 106 columns):
id                                              int64
listing_url                                     object
scrape_id                                       int64
last_scraped                                    object
name                                            object
summary                                         object
space                                           object
description                                     object
experiences_offered                             object
neighborhood_overview                           object
notes                                           object
transit                                         object
access                                          object
interaction                                     object
house_rules                                     object
thumbnail_url                                   float64
medium_url                                      float64
picture_url                                     object
xl_picture_url                                  float64
host_id                                         int64
host_url                                        object
host_name                                       object
host_since                                      object
host_location                                   object
host_about                                      object
host_response_time                              object
host_response_rate                              object
host_acceptance_rate                            float64
host_is_superhost                               object
host_thumbnail_url                              object
host_picture_url                                object
host_neighbourhood                              object
host_listings_count                             float64
host_total_listings_count                       float64
host_verifications                              object
host_has_profile_pic                            object
host_identity_verified                          object
street                                          object
neighbourhood                                   object
neighbourhood_cleansed                          object
neighbourhood_group_cleansed                    float64
city                                            object
state                                           object
zipcode                                         object
market                                          object
smart_location                                  object
country_code                                    object
country                                         object
latitude                                        float64
longitude                                       float64
is_location_exact                               object
property_type                                   object
room_type                                       object
accommodates                                    int64
bathrooms                                       float64
bedrooms                                        float64
beds                                            float64
bed_type                                        object
amenities                                       object
square_feet                                     float64
price                                           object
weekly_price                                    object
monthly_price                                   object
security_deposit                                object
cleaning_fee                                    object
guests_included                                 int64
extra_people                                    object
minimum_nights                                  int64
maximum_nights                                  int64
minimum_minimum_nights                          int64
maximum_minimum_nights                          int64
minimum_maximum_nights                          int64
maximum_maximum_nights                          int64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                object
has_availability                                object
availability_30                                 int64
availability_60                                 int64
availability_90                                 int64
availability_365                                int64
calendar_last_scraped                           object
number_of_reviews                               int64
number_of_reviews_ltm                           int64
first_review                                    object
last_review                                     object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
requires_license                                object
license                                         object
jurisdiction_names                              object
instant_bookable                                object
is_business_travel_ready                        object
cancellation_policy                             object
require_guest_profile_picture                   object
require_guest_phone_verification                object
calculated_host_listings_count                  int64
calculated_host_listings_count_entire_homes     int64
calculated_host_listings_count_private_rooms    int64
calculated_host_listings_count_shared_rooms     int64
reviews_per_month                               float64
dtypes: float64(23), int64(21), object(62)
memory usage: 6.9+ MB

In [139]:
#checking if any columns have null
pd.isnull(df).any()

id                                              False
listing_url                                     False
scrape_id                                       False
last_scraped                                    False
name                                            False
                                                ...
calculated_host_listings_count                  False
calculated_host_listings_count_entire_homes     False
calculated_host_listings_count_private_rooms    False
calculated_host_listings_count_shared_rooms     False
reviews_per_month                                True
Length: 106, dtype: bool

In [153]:
df.dropna(how='all')
df.dropna(thresh=2)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,958,https://www.airbnb.com/rooms/958,20191204162709,2019-12-04,"Bright, Modern Garden Unit - 1BR/1B",New update: the house next door is under const...,"Newly remodeled, modern, and bright garden uni...",New update: the house next door is under const...,none,*Quiet cul de sac in friendly neighborhood *St...,...,f,f,moderate,f,f,1,1,0,0,1.79
1,3850,https://www.airbnb.com/rooms/3850,20191204162709,2019-12-04,Charming room for two,Your own private room plus access to a shared ...,This room can fit two people. Nobody else will...,Your own private room plus access to a shared ...,none,"This is a quiet, safe neighborhood on a substa...",...,f,f,strict_14_with_grace_period,f,f,3,0,3,0,1.38
2,5858,https://www.airbnb.com/rooms/5858,20191204162709,2019-12-05,Creative Sanctuary,NaN,We live in a large Victorian house on a quiet ...,We live in a large Victorian house on a quiet ...,none,I love how our neighborhood feels quiet but is...,...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,0.86
3,7918,https://www.airbnb.com/rooms/7918,20191204162709,2019-12-04,A Friendly Room - UCSF/USF - San Francisco,Nice and good public transportation. 7 minute...,"Settle down, S.F. resident, student, hospital,...",Nice and good public transportation. 7 minute...,none,"Shopping old town, restaurants, McDonald, Whol...",...,f,f,strict_14_with_grace_period,f,f,9,0,9,0,0.14
4,8142,https://www.airbnb.com/rooms/8142,20191204162709,2019-12-04,Friendly Room Apt. Style -UCSF/USF - San Franc...,Nice and good public transportation. 7 minute...,"Settle down, S.F. resident, student, hospital,...",Nice and good public transportation. 7 minute...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,9,0,9,0,0.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8528,40544136,https://www.airbnb.com/rooms/40544136,20191204162709,2019-12-04,Entire apartment in Pacific Heights/beautiful ...,A place for zen with a beautiful patio and bac...,NaN,A place for zen with a beautiful patio and bac...,none,NaN,...,t,f,flexible,f,f,2,1,1,0,NaN
8529,40546145,https://www.airbnb.com/rooms/40546145,20191204162709,2019-12-04,Huge Private Room; 8 min to Dwntwn SF & SFO,We are kind and friendly people looking for wo...,NaN,We are kind and friendly people looking for wo...,none,NaN,...,t,f,flexible,f,f,2,0,2,0,NaN
8530,40547706,https://www.airbnb.com/rooms/40547706,20191204162709,2019-12-04,Welcome onboard a beautiful Sailboat!,"Experience a beautiful and cozy, spacious and ...","The boat comes furnished with blankets, small ...","Experience a beautiful and cozy, spacious and ...",none,The Location : Treasure Island Marina offers ...,...,t,f,moderate,f,f,1,1,0,0,NaN
8531,40560328,https://www.airbnb.com/rooms/40560328,20191204162709,2019-12-04,Lg 1 Bed/1 Bath w/ Living & Dining Rm in Top Area,"(This same unit, listed as a 2 bedroom has 5 o...",This very large 1 bedroom/1 bathroom/living ro...,"(This same unit, listed as a 2 bedroom has 5 o...",none,There are 2 parks in the neighborhood. There i...,...,f,f,moderate,f,f,2,2,0,0,NaN
8532,40569280,https://www.airbnb.com/rooms/40569280,20191204162709,2019-12-04,Clean Spacious Room in Central SF Flat - 30 Da...,"Located in the heart of the Mission District, ...",I have custom designed this home for our famil...,"Located in the heart of the Mission District, ...",none,In my totally biased opinion: the Mission dist...,...,t,f,strict_14_with_grace_period,f,f,8,1,7,0,NaN

In [142]:
df['price'] = df['price'].str.lstrip('$')
df['weekly_price']= df['weekly_price'].str.lstrip('$')
df['monthly_price']= df['monthly_price'].str.lstrip('$')
df['security_deposit'] = df['security_deposit'].str.lstrip('$')
df['cleaning_fee']= df['cleaning_fee'].str.lstrip('$')
df['extra_people']= df['extra_people'].str.lstrip('$')

In [143]:
# changing object to numeric values
numeric_cols = ['price','weekly_price','monthly_price','monthly_price',
                'security_deposit','cleaning_fee','extra_people']

In [100]:
## keep getting errors for trying to iterate over multiple columns
def omit_dollar_sign(row):
    return df[numeric_cols].lstrip('$')
#f[numeric_cols].apply(omit_dollar_sign)

#df[numeric_cols].apply()

In [149]:
df[numeric_cols].describe()

,price,weekly_price,monthly_price,monthly_price,security_deposit,cleaning_fee,extra_people
count,8533,1053,1026,1026,6774,7574,8533
unique,526,321,310,310,96,194,81
top,150.00,"1,000.00","3,500.00","3,500.00",0.00,100.00,0.00
freq,274,49,42,42,2257,754,4715

In [150]:
df[numeric_cols] #.fillna(0, inplace = True) #this function makes it return null
# for NaN, want to make calculations & add another column that flags that it's a manual adjustment

,price,weekly_price,monthly_price,monthly_price,security_deposit,cleaning_fee,extra_people
0,170.00,"1,120.00","4,200.00","4,200.00",100.00,100.00,25.00
1,99.00,NaN,NaN,NaN,0.00,10.00,20.00
2,235.00,"1,600.00","5,500.00","5,500.00",NaN,100.00,0.00
3,65.00,485.00,"1,685.00","1,685.00",200.00,50.00,12.00
4,65.00,490.00,"1,685.00","1,685.00",200.00,50.00,12.00
...,...,...,...,...,...,...,...
8528,95.00,NaN,NaN,NaN,0.00,50.00,0.00
8529,55.00,NaN,NaN,NaN,NaN,NaN,0.00
8530,100.00,NaN,NaN,NaN,500.00,100.00,0.00
8531,295.00,NaN,NaN,NaN,NaN,NaN,0.00
8532,60.00,NaN,NaN,NaN,NaN,NaN,0.00

In [157]:
df[numeric_cols].apply(pd.to_numeric, errors = 'coerce') #making it into a numeric

,price,weekly_price,monthly_price,monthly_price,security_deposit,cleaning_fee,extra_people
0,170.0,NaN,NaN,NaN,100.0,100.0,25.0
1,99.0,NaN,NaN,NaN,0.0,10.0,20.0
2,235.0,NaN,NaN,NaN,NaN,100.0,0.0
3,65.0,485.0,NaN,NaN,200.0,50.0,12.0
4,65.0,490.0,NaN,NaN,200.0,50.0,12.0
...,...,...,...,...,...,...,...
8528,95.0,NaN,NaN,NaN,0.0,50.0,0.0
8529,55.0,NaN,NaN,NaN,NaN,NaN,0.0
8530,100.0,NaN,NaN,NaN,500.0,100.0,0.0
8531,295.0,NaN,NaN,NaN,NaN,NaN,0.0
8532,60.0,NaN,NaN,NaN,NaN,NaN,0.0

In [159]:
df[numeric_cols].describe()

,price,weekly_price,monthly_price,monthly_price,security_deposit,cleaning_fee,extra_people
count,8533,1053,1026,1026,6774,7574,8533
unique,526,321,310,310,96,194,81
top,150.00,"1,000.00","3,500.00","3,500.00",0.00,100.00,0.00
freq,274,49,42,42,2257,754,4715

In [ ]:
# want to omit null columns if it is an object